% clear variables and close windows
clear all;
close all;
clc;

%%% Start READ REAL DATA
load Results.mat % the workspace results are generated by the code FPCAreal_data.m
load('xData.txt','-ascii');
load('Is.txt','-ascii');
load('tickdatayear.txt','-ascii');

%%% End READ REAL DATA

%%% Start PLOT FIGURE

% define axis
axis_x=linspace(min(mx),max(mx),50); % maturity
axis_y=linspace(min(my),max(my),50); % moneyness
[Xa,Ya] = meshgrid(axis_x,axis_y);

% interpolate data for the functional components
FFun1 = TriScatteredInterp(mx,my,V2b(:,1), 'linear');
FFun2 = TriScatteredInterp(mx,my,V2b(:,2), 'linear');
FFun3 = TriScatteredInterp(mx,my,V2b(:,3), 'linear');
FFun4 = TriScatteredInterp(mx,my,V2b(:,4), 'linear');
FFun5 = TriScatteredInterp(mx,my,V2b(:,5), 'linear');
FFun6 = TriScatteredInterp(mx,my,V2b(:,6), 'linear');
FFun7 = TriScatteredInterp(mx,my,V2b(:,7), 'linear');
FFun8 = TriScatteredInterp(mx,my,V2b(:,8), 'linear');

Za1b=FFun1(Xa,Ya);
Za2b=FFun2(Xa,Ya);
Za3b=FFun3(Xa,Ya);
Za4b=FFun4(Xa,Ya);
Za5b=FFun5(Xa,Ya);
Za6b=FFun6(Xa,Ya);
Za7b=FFun7(Xa,Ya);
Za8b=FFun8(Xa,Ya);

figure(2)
hFig = figure(2);
set(hFig, 'Position', 0.8*[500 500 1000 900])

subplot(3,2,1)
surfl(Xa,Ya,-Za1b);
set(gca,'XTick',[0.50 0.75 1 1.25 1.50])
set(gca,'YTick',[0 0.25 0.50 0.75 1 ])
xh=xlabel('Moneyness')
yh=ylabel('Maturity')
zh=zlabel('$$\hat{\gamma}^{(d)}_{1,T}$$')
set(zh,'Interpreter','latex')
set([xh,yh,zh],'fontsize',10)
set(gca, 'fontsize',10)

subplot(3,2,2)
plot(xData,-loadsb(1,Is),'blue')
xlim([min(xData) max(xData)])
zh=ylabel('$$\hat{\delta}_{1,T}$$')
set(zh,'Interpreter','latex')
set(gca,'XTick',tickdatayear([1,3,5,7,9,11]))
set(gca,'XTickLabel',[2002 2004  2006 2008 2010 2012])
set(gca, 'LooseInset', get(gca, 'TightInset'));
set([xh,yh],'fontsize',10)
set(gca, 'fontsize',10)

subplot(3,2,5)
surfl(Xa,Ya,-Za7b);
set(gca,'XTick',[0.50 0.75 1 1.25 1.50])
set(gca,'YTick',[0 0.25 0.50 0.75 1 ])
xh=xlabel('Moneyness')
yh=ylabel('Maturity')
zh=zlabel('$$\hat{\gamma}^{(d)}_{7,T}$$')
set(zh,'Interpreter','latex')
set([xh,yh,zh],'fontsize',10)
set(gca, 'fontsize',10)

subplot(3,2,6)
plot(xData,-loadsb(7,Is),'blue')
xlim([min(xData) max(xData)])
zh=ylabel('$$\hat{\delta}_{7,T}$$')
set(zh,'Interpreter','latex')
set(gca,'XTick',tickdatayear([1,3,5,7,9,11]))
set(gca,'XTickLabel',[2002 2004  2006 2008 2010 2012])
set(gca, 'LooseInset', get(gca, 'TightInset'));
set([xh,yh],'fontsize',10)
set(gca, 'fontsize',10)

subplot(3,2,3)
surfl(Xa,Ya,-Za3b);
set(gca,'XTick',[0.50 0.75 1 1.25 1.50])
set(gca,'YTick',[0 0.25 0.50 0.75 1 ])
xh=xlabel('Moneyness')
yh=ylabel('Maturity')
zh=zlabel('$$\hat{\gamma}^{(d)}_{3,T}$$')
set(zh,'Interpreter','latex')
set([xh,yh,zh],'fontsize',10)
set(gca, 'fontsize',10)

subplot(3,2,4)
plot(xData,-loadsb(3,Is),'blue')
xlim([min(xData) max(xData)])
zh=ylabel('$$\hat{\delta}_{3,T}$$')
set(zh,'Interpreter','latex')
set(gca,'XTick',tickdatayear([1,3,5,7,9,11]))
set(gca,'XTickLabel',[2002 2004  2006 2008 2010 2012])
set(gca, 'LooseInset', get(gca, 'TightInset'));
set([xh,yh],'fontsize',10)
set(gca, 'fontsize',10)

%%% End PLOT FIGURE
